### ISSUE TITLE
Proposal: YAML definitions

### ISSUE THREAD

**Issue by simon816** [ddevault/pass-rotate#45]
While there are inevitably going to be websites that require custom logic, I suspect the majority could be simplified to the point where all that's needed is a YAML file describing the login/change password process.

There are several motivating reasons to do this:

 * Easier to define providers
 * Abstract the bore of managing HTTP requests, sessions, form finding, etc
 * Easier maintenance
 * YAML files could potentially be generated / consumed by other programs (I'm thinking a browser extension that you can interactively define a provider YAML)

To test the feasibility of this idea, I have written a mock-up implementation: https://gist.github.com/simon816/1969e4fd84666b9cc81b5c1e049c5b3f

For example, the Wikipedia provider can be defined like so:
```yaml
---
name: Wikipedia
domains:
  - wikipedia.org
flows:
  - get_url: "https://en.wikipedia.org/w/index.php?title=Special:UserLogin"
    match_form:
      - field: "wpName"
        fill: username
      - field: "wpPassword"
        fill: old_password
    action:
      type: submit_form
      success:
        status: 200
        text_match_not: "Incorrect username or password entered"
  - get_url: "https://en.wikipedia.org/w/index.php?title=Special:ChangeCredentials/MediaWiki\\Auth\\PasswordAuthenticationRequest"
    match_form:
      - field: "password"
        fill: new_password
      - field: "retype"
        fill: new_password
    action: submit_form
```

Thoughts?
